### PR TITLE
feat: use `--output yaml` instead of kubectl command

### PR DESCRIPTION
**Pull request by mingxiao**

### CODE REVIEW

**Comment by trisberg** [comment]
Is there some context for this PR?

**Review by paulcwarren — APPROVED** [review]
These changes are a "bug fix" that cleans up an overly complex apply command.

**Review by paulcwarren — CHANGES_REQUESTED** [review]
I think it is safe to remove the OUTPUT_TO_NULL_COMMAND as it is no longer used

**Review by paulcwarren — APPROVED** [review]
These changes fix an overly complex apply command bug.  The new apply command requires version 0.11.1 of the apps plugin.  PM do not require these files to be backward compatible.

**Pull request merged**
