### PR TITLE
Updates client.yaml for appsso-starter-java

### PR DESCRIPTION
**Pull request by ddubson**
Changes are to simplify external use of client.yaml with ytt. 'Secure a Workload' docs instruct the end-user on how to apply this resource.

### CODE REVIEW

**Comment by trisberg** [comment]
Can we add something to the README explaining the ytt steps that are needed. Also, should the links to the docs be updated? They point to tap-1.3 docs.

**Comment by trisberg** [comment]
There is also a fix for the docs link in this PR: https://github.com/vmware-tanzu/application-accelerator-samples/pull/161

**Comment by ddubson** [comment]
"Secure a Workload" docs page is getting an update as per https://github.com/pivotal/docs-tap/pull/2122 - I will update the README with example usage.

I'll update the links in the README as well.

**Comment by ddubson** [comment]
@trisberg - updated README and links within.

**Comment by trisberg** [comment]
Any thoughts for how to keep this README in sync with TAP docs - once we release this for TAP 1.5 it will point to potentially outdated docs for TAP 1.4.

**Comment by ddubson** [comment]
It would be ideal if there was a `latest` docs path but I'm not aware of that existing, it's currently based on version if I'm not mistaken. Has this been done with other teams to your knowledge?

I can make a via.vmware.com shortlinks for the 3 links referenced in the commit.

**Comment by trisberg** [comment]
The link really should be for the docs that are to be released that goes with the release of the accelerators, but they are not publicly available at the time we create the bundle. Not sure what the best solution is. I typically avoid linking to TAP docs from any accelerators for this reason.

**Comment by ddubson** [comment]
Is this a blocker for this merge or can these changes be merged?

**Pull request merged**
